"""
PSNR, SSIM, RMSE, MSE, MAE, and RS analysis for adversarial examples.

This script computes perceptual-quality statistics between clean preprocessed
model inputs and adversarial inputs generated by FGSM and PGD.

It also recomputes clean/adversarial MSE, RMSE, MAE, RS, and threshold exceedance
rates to verify consistency with the manuscript tables.

Assumptions used in the manuscript:
- Test images are defined by TEST_IMAGE_DIR in config.py
- Ground-truth labels are defined by TEST_LABEL_CSV in config.py
- Ground-truth steering angles are in degrees
- Model outputs are in radians
- Attack loss uses radians
- Predictions are converted to degrees for MSE, RMSE, MAE, and RS reporting
- Attacks are applied in normalized YUV model-input space [0,1]
- All outputs go to RESULTS_DIR / "perceptual_quality"
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import os
import csv
import numpy as np
import pandas as pd
import cv2
import tensorflow as tf

from skimage.metrics import peak_signal_noise_ratio, structural_similarity

from preprocessing.preprocess_australian import preprocess_image
from models.pilotnet import PilotNet
from models.resnet18 import ResNet18Steering
from config import (
    TEST_IMAGE_DIR,
    TEST_LABEL_CSV,
    RESULTS_DIR,
    FIGURES_DIR,
    WEIGHTS_PILOTNET_US,
    WEIGHTS_PILOTNET_FLIPPED,
    WEIGHTS_PILOTNET_PARTIAL_FT_US,
    WEIGHTS_PILOTNET_PARTIAL_FT_FLIPPED,
    WEIGHTS_RESNET_US,
    WEIGHTS_RESNET_FLIPPED,
    WEIGHTS_RESNET_PARTIAL_FT_US,
    WEIGHTS_RESNET_PARTIAL_FT_FLIPPED,
)


DATA_DIR = Path(TEST_IMAGE_DIR)
GROUND_TRUTH_CSV = Path(TEST_LABEL_CSV)
OUTPUT_DIR = Path(RESULTS_DIR) / "perceptual_quality"
EXAMPLES_DIR = OUTPUT_DIR / "non_exaggerated_examples"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
EXAMPLES_DIR.mkdir(parents=True, exist_ok=True)




RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)
tf.random.set_seed(RANDOM_SEED)



EXPERIMENTS = [
    # -------------------------
    # PilotNet
    # -------------------------
    {
        "architecture": "PilotNet",
        "strategy": "U.S. trained",
        "short_name": "us_trained",
        "weights": str(WEIGHTS_PILOTNET_US),
    },
    {
        "architecture": "PilotNet",
        "strategy": "Flipped U.S. trained",
        "short_name": "flipped_us_trained",
        "weights": str(WEIGHTS_PILOTNET_FLIPPED),
    },
    {
        "architecture": "PilotNet",
        "strategy": "Fine-tuned from U.S.-pretrained",
        "short_name": "finetuned_us_pretrained",
        "weights": str(WEIGHTS_PILOTNET_PARTIAL_FT_US),
    },
    {
        "architecture": "PilotNet",
        "strategy": "Fine-tuned from flipped-U.S.-pretrained",
        "short_name": "finetuned_flipped_us_pretrained",
        "weights": str(WEIGHTS_PILOTNET_PARTIAL_FT_FLIPPED),
    },

  
    {
        "architecture": "ResNet-18",
        "strategy": "U.S. trained",
        "short_name": "us_trained",
        "weights": str(WEIGHTS_RESNET_US),
    },
    {
        "architecture": "ResNet-18",
        "strategy": "Flipped U.S. trained",
        "short_name": "flipped_us_trained",
        "weights": str(WEIGHTS_RESNET_FLIPPED),
    },
    {
        "architecture": "ResNet-18",
        "strategy": "Fine-tuned from U.S.-pretrained",
        "short_name": "finetuned_us_pretrained",
        "weights": str(WEIGHTS_RESNET_PARTIAL_FT_US),
    },
    {
        "architecture": "ResNet-18",
        "strategy": "Fine-tuned from flipped-U.S.-pretrained",
        "short_name": "finetuned_flipped_us_pretrained",
        "weights": str(WEIGHTS_RESNET_PARTIAL_FT_FLIPPED),
    },
]


FGSM_SETTINGS = [
    {"epsilon": 0.01},
    {"epsilon": 0.03},
    {"epsilon": 0.05},
]

PGD_SETTINGS = [
    {"epsilon": 0.01, "alpha": 0.002, "iterations": 10},
    {"epsilon": 0.03, "alpha": 0.005, "iterations": 10},
    {"epsilon": 0.05, "alpha": 0.010, "iterations": 10},
]



SAVE_EXAMPLES = True

# Save only 2 frames per architecture + strategy.
NUM_EXAMPLE_FRAMES_PER_ARCH_STRATEGY = 2

SAVE_EXAMPLE_ATTACKS = ["FGSM", "PGD"]
SAVE_EXAMPLE_EPSILONS = [0.01, 0.03, 0.05]



def load_ground_truth(csv_path):
 

    ground_truth = {}

    with open(csv_path, mode="r", encoding="utf-8") as file:
        reader = csv.reader(file)
        headers = next(reader)

        print("CSV headers:", headers)

        for row in reader:
            if not row:
                continue

            try:
                if len(row) == 1:
                    parts = row[0].split()
                    frame_name = parts[0]
                    steering_angle = float(parts[1])
                else:
                    frame_name = row[0]
                    steering_angle = float(row[1])

                frame_id = str(frame_name)
                frame_id = frame_id.replace("frame_", "")
                frame_id = frame_id.replace(".jpg", "")
                frame_id = frame_id.replace(".png", "")
                frame_id = int(frame_id)

                ground_truth[frame_id] = steering_angle

            except Exception as e:
                print(f"Skipping row {row}: {e}")

    return ground_truth




def build_model(architecture):
    if architecture == "PilotNet":
        return PilotNet(input_shape=(66, 200, 3)).build_model()

    if architecture == "ResNet-18":
        return ResNet18Steering(input_shape=(66, 200, 3)).build_model()

    raise ValueError(f"Unknown architecture: {architecture}")




def fgsm_attack(model, clean_image, label_degrees, epsilon):


    image_tensor = tf.convert_to_tensor(clean_image, dtype=tf.float32)

    label_radians = label_degrees * np.pi / 180.0
    label_tensor = tf.convert_to_tensor([[label_radians]], dtype=tf.float32)

    with tf.GradientTape() as tape:
        tape.watch(image_tensor)
        prediction = model(tf.expand_dims(image_tensor, axis=0), training=False)
        loss = tf.keras.losses.MeanSquaredError()(label_tensor, prediction)

    gradients = tape.gradient(loss, image_tensor)
    signed_grad = tf.sign(gradients)

    adv_image = image_tensor + epsilon * signed_grad
    adv_image = tf.clip_by_value(adv_image, 0.0, 1.0)

    return adv_image.numpy()


def pgd_attack(model, clean_image, label_degrees, epsilon, alpha, iterations):


    image_tensor = tf.convert_to_tensor(clean_image, dtype=tf.float32)

    label_radians = label_degrees * np.pi / 180.0
    label_tensor = tf.convert_to_tensor([[label_radians]], dtype=tf.float32)

    adv_image = image_tensor + tf.random.uniform(
        image_tensor.shape,
        minval=-epsilon / 2.0,
        maxval=epsilon / 2.0,
        dtype=tf.float32,
    )

    adv_image = tf.clip_by_value(adv_image, 0.0, 1.0)

    for _ in range(iterations):
        with tf.GradientTape() as tape:
            tape.watch(adv_image)
            prediction = model(tf.expand_dims(adv_image, axis=0), training=False)
            loss = tf.keras.losses.MeanSquaredError()(label_tensor, prediction)

        gradients = tape.gradient(loss, adv_image)
        signed_grad = tf.sign(gradients)

        adv_image = adv_image + alpha * signed_grad

        perturbation = tf.clip_by_value(
            adv_image - image_tensor,
            -epsilon,
            epsilon,
        )

        adv_image = image_tensor + perturbation
        adv_image = tf.clip_by_value(adv_image, 0.0, 1.0)

    return adv_image.numpy()


def yuv_norm_to_rgb_uint8(yuv_norm):
 

    yuv_uint8 = np.clip(yuv_norm * 255.0, 0, 255).astype(np.uint8)
    rgb_uint8 = cv2.cvtColor(yuv_uint8, cv2.COLOR_YUV2RGB)

    return rgb_uint8


def save_clean_image_once(clean_yuv, clean_path):
 

    if os.path.exists(clean_path):
        return

    clean_rgb = yuv_norm_to_rgb_uint8(clean_yuv)
    cv2.imwrite(clean_path, cv2.cvtColor(clean_rgb, cv2.COLOR_RGB2BGR))


def save_adversarial_example(clean_yuv, adv_yuv, output_prefix):

    adv_rgb = yuv_norm_to_rgb_uint8(adv_yuv)
    clean_rgb = yuv_norm_to_rgb_uint8(clean_yuv)

    diff_rgb = np.abs(
        adv_rgb.astype(np.int16) - clean_rgb.astype(np.int16)
    ).astype(np.uint8)

    adv_path = f"{output_prefix}_adversarial.png"
    diff_path = f"{output_prefix}_absolute_difference.png"

    cv2.imwrite(adv_path, cv2.cvtColor(adv_rgb, cv2.COLOR_RGB2BGR))
    cv2.imwrite(diff_path, cv2.cvtColor(diff_rgb, cv2.COLOR_RGB2BGR))




def compute_psnr_ssim(clean_yuv, adv_yuv):


    psnr_value = peak_signal_noise_ratio(
        clean_yuv,
        adv_yuv,
        data_range=1.0,
    )

    ssim_value = structural_similarity(
        clean_yuv,
        adv_yuv,
        data_range=1.0,
        channel_axis=-1,
    )

    return psnr_value, ssim_value



def evaluate_condition(
    model,
    experiment,
    attack_name,
    setting,
    ground_truth,
    example_frames,
):
    architecture = experiment["architecture"]
    strategy = experiment["strategy"]
    short_name = experiment["short_name"]

    epsilon = setting["epsilon"]
    alpha = setting.get("alpha", np.nan)
    iterations = setting.get("iterations", np.nan)

    psnr_values = []
    ssim_values = []

    clean_predictions = []
    adversarial_predictions = []
    actuals = []

    per_image_rows = []

    print("=" * 80)
    print(f"{architecture} | {strategy} | {attack_name} | epsilon={epsilon}")

    example_key = (architecture, short_name)

    for frame_number, steering_angle in ground_truth.items():
        image_name = f"frame_{frame_number}.jpg"
        image_path = DATA_DIR / image_name

        if not os.path.exists(image_path):
            continue

        clean_yuv = preprocess_image(image_path).astype(np.float32)

        if attack_name == "FGSM":
            adv_yuv = fgsm_attack(
                model=model,
                clean_image=clean_yuv,
                label_degrees=steering_angle,
                epsilon=epsilon,
            )

        elif attack_name == "PGD":
            adv_yuv = pgd_attack(
                model=model,
                clean_image=clean_yuv,
                label_degrees=steering_angle,
                epsilon=epsilon,
                alpha=alpha,
                iterations=iterations,
            )

        else:
            raise ValueError("attack_name must be FGSM or PGD")

        clean_prediction_rad = model.predict(
            np.expand_dims(clean_yuv, axis=0),
            verbose=0,
        )[0][0]

        adversarial_prediction_rad = model.predict(
            np.expand_dims(adv_yuv, axis=0),
            verbose=0,
        )[0][0]

        clean_prediction_deg = clean_prediction_rad * 180.0 / np.pi
        adversarial_prediction_deg = adversarial_prediction_rad * 180.0 / np.pi

        clean_predictions.append(clean_prediction_deg)
        adversarial_predictions.append(adversarial_prediction_deg)
        actuals.append(steering_angle)

        psnr_value, ssim_value = compute_psnr_ssim(clean_yuv, adv_yuv)

        psnr_values.append(psnr_value)
        ssim_values.append(ssim_value)

        clean_error = clean_prediction_deg - steering_angle
        adversarial_error = adversarial_prediction_deg - steering_angle

        per_image_rows.append({
            "Architecture": architecture,
            "Strategy": strategy,
            "Attack": attack_name,
            "Epsilon": epsilon,
            "Alpha": alpha,
            "Iterations": iterations,
            "Frame": frame_number,

            "Ground_Truth": steering_angle,
            "Clean_Prediction": clean_prediction_deg,
            "Adversarial_Prediction": adversarial_prediction_deg,
            "Clean_Error": clean_error,
            "Adversarial_Error": adversarial_error,
            "Absolute_Clean_Error": abs(clean_error),
            "Absolute_Adversarial_Error": abs(adversarial_error),

            "PSNR": psnr_value,
            "SSIM": ssim_value,
        })

   
        if (
            SAVE_EXAMPLES
            and attack_name in SAVE_EXAMPLE_ATTACKS
            and any(np.isclose(epsilon, e) for e in SAVE_EXAMPLE_EPSILONS)
        ):
            
            if example_key not in example_frames:
                example_frames[example_key] = []

            selected_frames = example_frames[example_key]

            if (
                frame_number not in selected_frames
                and len(selected_frames) < NUM_EXAMPLE_FRAMES_PER_ARCH_STRATEGY
            ):
                selected_frames.append(frame_number)

            if frame_number in selected_frames:
                example_number = selected_frames.index(frame_number) + 1

                base_name = (
                    f"{architecture.replace('-', '')}_"
                    f"{short_name}_"
                    f"example{example_number}_"
                    f"frame{frame_number}"
                )

                clean_path = str(EXAMPLES_DIR / f"{base_name}_clean.png")
                save_clean_image_once(clean_yuv, clean_path)

                adv_prefix = str(
                    EXAMPLES_DIR / f"{base_name}_{attack_name}_eps{epsilon}"
                )

                save_adversarial_example(clean_yuv, adv_yuv, adv_prefix)

    psnr_values = np.array(psnr_values, dtype=np.float64)
    ssim_values = np.array(ssim_values, dtype=np.float64)

    clean_predictions = np.array(clean_predictions, dtype=np.float64)
    adversarial_predictions = np.array(adversarial_predictions, dtype=np.float64)
    actuals = np.array(actuals, dtype=np.float64)

    if len(psnr_values) == 0:
        print("No valid images found for this condition.")
        return None, None

    clean_errors = clean_predictions - actuals
    adversarial_errors = adversarial_predictions - actuals

    clean_abs_errors = np.abs(clean_errors)
    adversarial_abs_errors = np.abs(adversarial_errors)

    clean_mse = np.mean(clean_errors ** 2)
    adversarial_mse = np.mean(adversarial_errors ** 2)

    clean_rmse = np.sqrt(clean_mse)
    adversarial_rmse = np.sqrt(adversarial_mse)

    clean_mae = np.mean(clean_abs_errors)
    adversarial_mae = np.mean(adversarial_abs_errors)

    rs = clean_mse / adversarial_mse if adversarial_mse != 0 else np.nan

    exceed_5 = np.mean(adversarial_abs_errors > 5.0) * 100.0
    exceed_10 = np.mean(adversarial_abs_errors > 10.0) * 100.0
    exceed_15 = np.mean(adversarial_abs_errors > 15.0) * 100.0

    summary_row = {
        "Architecture": architecture,
        "Strategy": strategy,
        "Attack": attack_name,
        "Epsilon": epsilon,
        "Alpha": alpha,
        "Iterations": iterations,
        "N": len(psnr_values),

        "Clean_MSE": clean_mse,
        "Adversarial_MSE": adversarial_mse,
        "Clean_RMSE": clean_rmse,
        "Adversarial_RMSE": adversarial_rmse,
        "Clean_MAE": clean_mae,
        "Adversarial_MAE": adversarial_mae,
        "RS": rs,

        "Adv_Error_>5deg_%": exceed_5,
        "Adv_Error_>10deg_%": exceed_10,
        "Adv_Error_>15deg_%": exceed_15,

        "PSNR_Mean": np.mean(psnr_values),
        "PSNR_Std": np.std(psnr_values),
        "PSNR_Median": np.median(psnr_values),
        "PSNR_Min": np.min(psnr_values),
        "PSNR_Max": np.max(psnr_values),

        "SSIM_Mean": np.mean(ssim_values),
        "SSIM_Std": np.std(ssim_values),
        "SSIM_Median": np.median(ssim_values),
        "SSIM_Min": np.min(ssim_values),
        "SSIM_Max": np.max(ssim_values),
    }

    per_image_df = pd.DataFrame(per_image_rows)

    per_image_file = OUTPUT_DIR / (
        f"{architecture.replace('-', '')}_{short_name}_{attack_name}_eps{epsilon}_per_image_metrics.csv"
    )

    per_image_df.to_csv(per_image_file, index=False)

    print("Summary:")
    print(summary_row)
    print(f"Saved per-image CSV: {per_image_file}")

    return summary_row, per_image_file



def main():
    print("Loading ground truth...")
    ground_truth = load_ground_truth(GROUND_TRUTH_CSV)
    print(f"Loaded {len(ground_truth)} ground-truth labels.")

    all_summary_rows = []

    
    example_frames = {}

    for experiment in EXPERIMENTS:
        weights_path = experiment["weights"]

        if not os.path.exists(weights_path):
            print("=" * 80)
            print("WARNING: Missing weights file, skipping:")
            print(weights_path)
            continue

        print("=" * 80)
        print(f"Loading model: {experiment['architecture']} | {experiment['strategy']}")
        print(f"Weights: {weights_path}")

        model = build_model(experiment["architecture"])
        model.load_weights(weights_path)

        # FGSM
        for setting in FGSM_SETTINGS:
            summary_row, _ = evaluate_condition(
                model=model,
                experiment=experiment,
                attack_name="FGSM",
                setting=setting,
                ground_truth=ground_truth,
                example_frames=example_frames,
            )

            if summary_row is not None:
                all_summary_rows.append(summary_row)

        # PGD
        for setting in PGD_SETTINGS:
            summary_row, _ = evaluate_condition(
                model=model,
                experiment=experiment,
                attack_name="PGD",
                setting=setting,
                ground_truth=ground_truth,
                example_frames=example_frames,
            )

            if summary_row is not None:
                all_summary_rows.append(summary_row)

        tf.keras.backend.clear_session()

    summary_df = pd.DataFrame(all_summary_rows)

    summary_file = OUTPUT_DIR / "perceptual_quality_PSNR_SSIM_RMSE_summary_all_models.csv"

    summary_df.to_csv(summary_file, index=False)

    print("=" * 80)
    print("DONE")
    print("Saved full summary CSV to:")
    print(summary_file)
    print("Saved non-exaggerated examples to:")
    print(EXAMPLES_DIR)


if __name__ == "__main__":
    main()
